name: satellite-processing-without-sf
channels:
  - conda-forge
  - defaults
dependencies:
  - basemap==1.2.0
  - cartopy==0.16.0
  - matplotlib==3.0.3
  - netCDF4==1.4.0
  - numpy==1.15.4
  - pandas==0.23.4
  - requests==2.20.0
  - xarray==0.10.9